### ISSUE TITLE
Publishable resource

### ISSUE THREAD

**Issue by nueko** [GrahamCampbell/Laravel-Exceptions#101]
Hi, just wonder how to customize the response.

**Comment by vinkla** [comment]
You can use the [exception displayers](https://github.com/GrahamCampbell/Laravel-Exceptions#exception-displayers).

**Comment by GrahamCampbell** [comment]
Yes, @vinkla is correct. That is rather the entire point of this package, to facilitate powerful, expressive, customization, though OOP.

**Comment by GrahamCampbell** [comment]
That is rather the entire point of this package, to facilitate powerful, expressive, customization, though OOP.
