### ISSUE TITLE
AuthenticationException is rendered on routes with middleware auth instead of redirect to login page

### ISSUE THREAD

**Issue by chepe263** [GrahamCampbell/Laravel-Exceptions#107]
Laravel 5.4 & Whoops

When using Laravel's `Illuminate\Foundation\Exceptions\Handler` and visiting a protected route with auth middleware, the browser is redirected to a login page.  (expected behaviour)

When using `GrahamCampbell\Exceptions\NewExceptionHandler` an `AuthenticationException` is rendered and not redirected to login page. (unexpected behaviour)

Looking at [Laravel handler](https://github.com/laravel/framework/blob/5.4/src/Illuminate/Foundation/Exceptions/Handler.php#L113) there is a check for `AuthenticationException` and the function `unauthenticated` is called

I couldn't find something similar on [`ExceptionHandlerTrait`
](https://github.com/GrahamCampbell/Laravel-Exceptions/blob/master/src/ExceptionHandlerTrait.php#L82)

The solution is to change the render function on `App\Exceptions\Handler` to take this into account

```
    public function render($request, Exception $exception)
    {
		if ($exception instanceof \Illuminate\Auth\AuthenticationException){
			return $this->unauthenticated($request, $exception);
		}
                return parent::render($request, $exception);
    }
```

**Comment by mikeerickson** [comment]
Fantastic!  I just hit this every thing this afternoon and was gonna debug it tomorrow.  @grahamcampbell do you want me to PR, or will you address it?  I can PR tomorrow morning.

**Comment by mikeerickson** [comment]
@chepe263 unless of course you wanted to PR if before I get to it, that would be swell 🤓

**Comment by chepe263** [comment]
If you can PR it, go on.

**Comment by mikeerickson** [comment]
@chepe263 sounds good, will take care of it in the morning

**Comment by chepe263** [comment]
Thank you \^o^/

**Comment by mikeerickson** [comment]
All done, here is PR https://github.com/GrahamCampbell/Laravel-Exceptions/pull/108

@chepe263 @GrahamCampbell

**Comment by GrahamCampbell** [comment]
Thanks everyone. 👍

**Comment by 4bd3ll4z1z** [comment]
Thank you! You saved me

**Comment by josegus** [comment]
so, this was never merged, right? I'm using v12.1 with laravel 6.0 and I still have to ask if the exception is instance of AuthException.

I also made my own AuthException and my own AuthTransformer, but the exception is not being transformed.

**Comment by 4n70w4** [comment]
The same issue

**Comment by GrahamCampbell** [comment]
This is a feature, not a bug. Applications that return 301 instead of 401 are violating the HTTP spec. As I said above, if you want this wrong behaviour, you can implement it yourself - this package was specifically designed so that it can be customised using code.

**Comment by GrahamCampbell** [comment]
Something I do is include JS on HTML error pages for 401's which redirects to the login screen. That way, the correct HTTP error code is presented, and the UX is good.
