### ISSUE TITLE
Instance of Illuminate\Log\Writer passed to Constructor

### ISSUE THREAD

**Issue by tylernathanreed** [GrahamCampbell/Laravel-Exceptions#115]
When setting up this packaging within a fresh Laravel installation, I get the following error:

> Argument 1 passed to Illuminate\Foundation\Exceptions\Handler::__construct() must implement interface Illuminate\Contracts\Container\Container, instance of Illuminate\Log\Writer given

This is because the Exception Handler is passing the Log Writer instead of the Container instance.

Extending the `NewExceptionHandler` class fixes this. However, the current readme does not explain this. It just states, "You then MUST change your `App\Exceptions\Handler` class to extend `GrahamCampbell\Exceptions\ExceptionHandler`.".

I'd like to suggest that either the readme be updated to tell developers to extend the new Exception Handler (which I believe it used to), or to replace the Exception Handler with the New Exception Handler (Seeing as legacy versions of Laravel are slowly no longer being supported by this package, this would be a logical next-step, and wouldn't require changing the readme).

So I don't know if this is a documentation issue or if the readme is correct (In which case this is considered a bug). Either way, this issue isn't very easy to figure out, as it just results in a Server 500 error with no messages.

**Comment by GrahamCampbell** [comment]
> Extending the NewExceptionHandler class fixes this. However, the current readme does not explain this. It just states, "You then MUST change your App\Exceptions\Handler class to extend GrahamCampbell\Exceptions\ExceptionHandler.".

That's because the readme is for v10 of this package, as yet unreleased. :)

**Comment by GrahamCampbell** [comment]
Please see the docs for the current release: https://github.com/GrahamCampbell/Laravel-Exceptions/tree/v9.3.0.
