### ISSUE TITLE
Custom exception identifier?

### ISSUE THREAD

**Issue by markspolakovs** [GrahamCampbell/Laravel-Exceptions#116]
Is it possible to register a custom `ExceptionIdentifier`?

**Use case:** I report my exceptions to Sentry and would like to show the Sentry ID in my interface, instead of Laravel-Exceptions' generated ID.

**Comment by GrahamCampbell** [comment]
Thanks for getting in touch. Yes, it is. Just register a new class that extends our `ExceptionIdentifier`, with the laravel container, and it'll get used, so long as you put your service provider after ours. :)
