### ISSUE TITLE
The given data failed to pass validation.

### ISSUE THREAD

**Issue by Naxon** [GrahamCampbell/Laravel-Exceptions#117]
Laravel 5.4

Instead of redirecting to the previous route with the errors, I get the above message.

**Comment by GrahamCampbell** [comment]
That would be the correct behaviour I think?

If you want to redirect back, then you'll need to add a custom displayer, or catch and redirect in your controller.

**Comment by Naxon** [comment]
When using Laravel's default exception handler, if the validator fails, the user is redirected back to the form with the validation errors. Is there a particular reason not to keep the same behavior in your handler?

**Comment by GrahamCampbell** [comment]
I don't like the default behaviour in Laravel. :P

This package is an opinionated total replacement of Laravel's exception handling system.
