### ISSUE TITLE
Please provide usage examples and detailed documentation.

### ISSUE THREAD

**Issue by jschlies** [GrahamCampbell/Laravel-Exceptions#118]
Please provide usage examples and detailed documentation or point to other sources that do so.

**Comment by markdieselcore** [comment]
Agreed. Not going to use the package if you can't be bothered to at least demo how you would use it.

**Comment by jschlies** [comment]
I will be providing this shortly. Probably after Saturday.

**Comment by jschlies** [comment]
Sorry, I withdraw that comment.

**Comment by GrahamCampbell** [comment]
> If you can't be bothered to at least demo how you would use it.

I find this very rude. We're open to contributions if you "can be bothered to" contribute to the documentation. This is an open source project.

**Comment by jschlies** [comment]
@GrahamCampbell 
While I agree that @markdieselcore 's comment was a bit flippant, but please bear in mind that  we need a tool such as this and it is my boss's opinion that a poorly documented Github is a bad Github. We'd like the idea here and we would like to participate more fully in this but lacking reasonable documentation (install, usage), we'll need to fork or pass in general. Once it exists, we'd be happy to contribute to the doc but writing it from scratch reminds me of the story of 3 blind guys and an elephant.

**Comment by GrahamCampbell** [comment]
The readme already covers install and setup,and it also explains how things work as an overview. The best way to understand the rest is to read the code. I am unable to explain how it works in a shorter way than the code does.

**Comment by markdieselcore** [comment]
I’m not trying to be rude about it. I’m just being upfront. You don’t have to write complete documentation, but you are catering to an audience that is comfortable with the principle of, “code that’s expressive to write”. All you have to do, at bare minimum, is give an example specifying the file name, a few mock lines of code, showcasing how you would use it and that’s it. It’s meant to wet our appetite. If I like what I see, I’ll dig into the code. But I don’t have time to read the source code of every package I come across.

**Comment by GrahamCampbell** [comment]
Example usage: https://github.com/CachetHQ/Cachet/tree/2.4/app/Foundation/Exceptions. Also in code. My point is you own code to use it, will look the same as the package code, so just read the package code.

**Comment by GrahamCampbell** [comment]
Those examples are just more examples of the same.
