### ISSUE TITLE
500 server error returned as text/plain

### ISSUE THREAD

**Issue by mseymour** [GrahamCampbell/Laravel-Exceptions#119]
I've noticed this after installing the package on a local 5.5 install after switching APP_ENV to production and APP_DEBUG to false, where if the application generates an error 500 (may it be due to some code error that I didn't pick up or otherwise), it simply returns "server error" as plain text instead of a proper HTML error page, either whatever is used by default or a custom one that I have in `/resources/views/errors/500.blade.php`.

Is this intended?

**Comment by GrahamCampbell** [comment]
It will do that if there was an exception thrown while rendering your view.

**Comment by GrahamCampbell** [comment]
It will have also logged that exception in your log file, so you can see what went wrong.
