### ISSUE TITLE
[9.4] No available `$exception->getMessage()` in views

### ISSUE THREAD

**Issue by andrey-helldar** [GrahamCampbell/Laravel-Exceptions#124]
Version of package: v.9.4.0
PHP: 5.6.32
Laravel: 5.4.36

// IndexController
```php
$is_error = true;
abort_if($is_error, 400, 'my message');
```

If using `Illuminate\Foundation\Exceptions\Handler`, then problem not found. But, If you use `GrahamCampbell\Exceptions\NewExceptionHandler`, then the code is accessing a nonexistent variable `$message`:

// in `errors.400`
```html
{{ $exception->getMessage() }}
```

**Comment by andrey-helldar** [comment]
I'm making corrections for it in #114.

I understood! That PR for version 10 was.

**Comment by andrey-helldar** [comment]
I created a PR #125

**Comment by GrahamCampbell** [comment]
This is a new feature, so I'm not looking to backport to the 9.4 maintenance line I'm afraid. Sorry.
