### ISSUE TITLE
Support request for Laravel Framework 5.6

### ISSUE THREAD

**Issue by roberto-aguilar** [GrahamCampbell/Laravel-Exceptions#126]
Is there any plans to support the 5.6 version of the framework?

Thanks!

**Comment by vinkla** [comment]
There will be a new version available in two weeks: https://github.com/GrahamCampbell/Laravel-Manager/pull/11#issuecomment-364654625

**Comment by roberto-aguilar** [comment]
Great to know, thanks @vinkla!

**Comment by GrahamCampbell** [comment]
V11.0 has just been released.
