### ISSUE TITLE
Translate text

### ISSUE THREAD

**Issue by jbrooksuk** [GrahamCampbell/Laravel-Exceptions#129]
Can we provide some translation strings.

**Comment by josegus** [comment]
I can help with spanish translation

**Comment by josegus** [comment]
@GrahamCampbell any idea how can I make the translations available so we can leave it as default or write a custom message for some exceptions?

**Comment by josegus** [comment]
@jbrooksuk maybe you can try the following:

1. Create your own errors.json file inside resources/ folder
2. Copy the entire errors.json file content from this package and translate it (google translate did it for me)
3. Register the ExceptionInfoInterface in your own AppServiceProvider:
![image](https://user-images.githubusercontent.com/13947849/66519077-910be700-eab4-11e9-9dbd-ba96df17bb11.png)

That's all, works for me:
![image](https://user-images.githubusercontent.com/13947849/66519364-2f984800-eab5-11e9-8109-d1fb1dd36ea3.png)
![image](https://user-images.githubusercontent.com/13947849/66519380-39ba4680-eab5-11e9-89a6-d4bc8985bc69.png)

**Comment by GrahamCampbell** [comment]
Closing due to lack of interest/an implementation.
