### ISSUE TITLE
Laravel 5.8

### ISSUE THREAD

**Issue by LavaToaster** [GrahamCampbell/Laravel-Exceptions#132]
I can see you've already updated the version constraints, but it would be super helpful if you could tag this in a release. 

:heart:

**Comment by GrahamCampbell** [comment]
I need to update the tests first. :)

**Comment by asivaneswaran** [comment]
Hey, any idea when this will be merged? :)

**Comment by GrahamCampbell** [comment]
It needs writing first. I'd be open to PRs to implement it.

**Comment by LavaToaster** [comment]
@GrahamCampbell I'd be happy to take a look at that, though I'm not sure what you're looking for specifically. Only issue I can see right now is the PHPUnit 9 warnings.

**Comment by GrahamCampbell** [comment]
Yeh, that's essentially it.

**Comment by GrahamCampbell** [comment]
I'll tag a new release today. :)
