### ISSUE TITLE
Does not record the exceptions in the telescope tab exceptions / Laravel 5.8

### ISSUE THREAD

**Issue by rcngo** [GrahamCampbell/Laravel-Exceptions#135]
Hi, does anyone use the telescope to view the exceptions? When I use this package, the telescope stops recording the exceptions. Can someone help me?

**Comment by GrahamCampbell** [comment]
I'm not familiar with telescope I'm afraid. Does it intercept the exceptions to handle them itself?

**Comment by rcngo** [comment]
So I was able to analyze the package changes the structure of the exception generated, so outside the standard of the Laravel exception the Telescope does not interpret as an exception.

**Comment by GrahamCampbell** [comment]
Thanks for the PR. Will be included in the v11.3.0 release shortly. :)
