### ISSUE TITLE
Laravel 5.0* support?

### ISSUE THREAD

**Issue by rattler72** [GrahamCampbell/Laravel-Exceptions#14]
Hi, it looks like this requires Laravel 5.1. Is there release for 5.0 distributions? 

I'm getting the following response on composer update:

```
- Installation request for graham-campbell/exceptions ~3.0 -> satisfiable by graham-campbell/exceptions[v3.0.0].
- graham-campbell/exceptions v3.0.0 requires illuminate/contracts 5.1.* -> no matching package found.
```

Thanks!

Stacey

**Comment by GrahamCampbell** [comment]
Yeh, there is. I've dropped support for Laravel 5.0 in the 3.x series, but the 2.x series supports Laravel 5.0, and so does the 1.x series.

**Comment by GrahamCampbell** [comment]
See the release notes: https://github.com/GrahamCampbell/Laravel-Exceptions/releases.

**Comment by rattler72** [comment]
Thank you!
