### ISSUE TITLE
Not able to handle 500 error through handler

### ISSUE THREAD

**Issue by miamarconi** [GrahamCampbell/Laravel-Exceptions#146]
I have installed Laravel 8 with GrahamCampbell/Exception 14.1. 
When I get 500 error then it just show plain text Internal Server Error and if I check error log then there is error 
local.ERROR: ReflectionException: Class GrahamCampbell\Exceptions\Transformers\AuthTransformer does not exist.

Code is: 

public function render($request, Throwable $e)
{
      return parent::render($request, $e);

}

Please help me to fix what exactly causing this

**Comment by GrahamCampbell** [comment]
This happens because you have published config for an old version of this package, and then a major version upgrade and not re-published the config file.

**Comment by miamarconi** [comment]
I have modified. What am I missing here ?

**Comment by GrahamCampbell** [comment]
> Class GrahamCampbell\Exceptions\Transformers\AuthTransformer does not exist.

**Comment by miamarconi** [comment]
I have executed php artisan vendor:publish command

**Comment by GrahamCampbell** [comment]
Great, if you re-cache config, the issue will go be resolved.

**Comment by GrahamCampbell** [comment]
If publishing did not override the exceptions.php config file, you will need to just edit the file yourself.

**Comment by miamarconi** [comment]
In config -> exceptions.php is the latest one after publish command, still getting same error

**Comment by GrahamCampbell** [comment]
Replace the file with https://github.com/GrahamCampbell/Laravel-Exceptions/blob/14.1/config/exceptions.php, and run `php artisan config:cache`.

**Comment by miamarconi** [comment]
Great!. This one worked. Thank you for help!
