### ISSUE TITLE
Laravel 6 with composer 2 could not found Laravel-Exceptions classes

### ISSUE THREAD

**Issue by hle-aashish** [GrahamCampbell/Laravel-Exceptions#147]
We have a project with Laravel 6 with `graham-campbell/exceptions` version `^13.1`. Recently we updated to Composer 2 and after the update, we are receiving the following issues:

```
Illuminate\Contracts\Container\BindingResolutionException
Target class [GrahamCampbell\Exceptions\ExceptionInfoInterface] does not exist.

Symfony\Component\Debug\Exception\FatalErrorException
Interface 'GrahamCampbell\Exceptions\Displayers\DisplayerInterface' not found

Illuminate\Contracts\Container\BindingResolutionException
Target class [GrahamCampbell\Exceptions\Transformers\ModelTransformer] does not exist.
```

It may be due to the upgrade of Composer to version 2. How can we fix these issues? Please, any solution is highly appreciated. Thank you.

**Comment by GrahamCampbell** [comment]
Did you also update from an earlier version of this package? Those interface names you describe only exist in version 12.x, and not 13.x or 14.x. You should check your app code for references to the old interfaces and classes, and change them.
