### ISSUE TITLE
TypeError: Argument 1 passed to GrahamCampbell\\Exceptions\\Filter\\VerboseFilter::__construct() must be of the type bool, string given

### ISSUE THREAD

**Issue by 4n70w4** [GrahamCampbell/Laravel-Exceptions#148]
Hi!
In case if `$app->config['app.debug']` is not boolean.
In the documentation of laravel, I see no restrictions that it must be bool.

**Comment by GrahamCampbell** [comment]
You do need to update your app.php config file to ensure that value is a bool. :)

**Comment by GrahamCampbell** [comment]
https://github.com/laravel/laravel/blob/v8.5.14/config/app.php#L42

**Comment by GrahamCampbell** [comment]
This was added in https://github.com/laravel/laravel/commit/5ddbfb845439fcd5a46c23530b8774421a931760, to stop these types of errors, but you should really make sure `APP_DEBUG` is either `true` or `false`.

**Comment by 4n70w4** [comment]
Okay, there is one more thing about which they forgot to write in the documentation for laravel and its upgrade guides =\

**Comment by 4n70w4** [comment]
But if I also use `symfony/error-handler` then I may have a need to pass closure as debug value =)

https://github.com/symfony/error-handler/blob/63acc71a4a2d8eb292eec2c8d0bb7229adb49eb0/ErrorRenderer/SerializerErrorRenderer.php#L43-L45

```php
if (!\is_bool($debug) && !\is_callable($debug)) {
	throw new \TypeError(sprintf('Argument 4 passed to "%s()" must be a boolean or a callable, "%s" given.', __METHOD__, get_debug_type($debug)));
}
```

https://github.com/symfony/error-handler/blob/63acc71a4a2d8eb292eec2c8d0bb7229adb49eb0/ErrorRenderer/SerializerErrorRenderer.php#L59

```php
$debug = \is_bool($this->debug) ? $this->debug : ($this->debug)($exception);
```

**Comment by GrahamCampbell** [comment]
You cannot set anything other than a boolean value in `app.debug`.

**Comment by 4n70w4** [comment]
I can it! Easy! =)

In random code of my app:

```
 $app->config['app.debug'] = function($a) { dd($a); };
```

One of many examples.

**Comment by GrahamCampbell** [comment]
Yes, but you are making an error by doing that.
