### ISSUE TITLE
creating Grandchild of  GrahamCampbell\Exceptions\Handler makes the exception handler crash

### ISSUE THREAD

**Issue by younes0** [GrahamCampbell/Laravel-Exceptions#15]
when a exception is raised, nothing happens, no output/no logs.
I have a "MyApp" exception handler which inherits from "MyCompany" exception handler which itself inherits from GrahamCampbell\Exceptions\Handler

**Comment by younes0** [comment]
UPDATE

**Comment by GrahamCampbell** [comment]
Well, I'm going to need more information than that.

**Comment by GrahamCampbell** [comment]
https://styleci.io/ has an exception handler that extends this one and it works just fine.

**Comment by GrahamCampbell** [comment]
Did you register the service provider for this package? Try putting it at the top of the list of registered service providers.

**Comment by GrahamCampbell** [comment]
https://github.com/StyleCI/StyleCI/blob/master/config/app.php#L122

**Comment by GrahamCampbell** [comment]
Did you bind this correctly? https://github.com/StyleCI/StyleCI/blob/master/bootstrap/app.php#L40

**Comment by younes0** [comment]
- I did bind correctly
- moved to the top the service provider registering, nothing changes
- no logs (nginx, app)

The package works fine when I bind the class which directly extends this package handler.
Not when the binded handler extends another class of mine which extends this package handler.

I'll make other tests with a fresh new laravel app and keep you informed 

thanks

**Comment by GrahamCampbell** [comment]
The fact that it's extending a child shouldn't make any difference. Could I see both classes please?

**Comment by younes0** [comment]
```php
// bootstrap/app.php
$app->singleton(
    Illuminate\Contracts\Debug\ExceptionHandler::class, 
    App\Exceptions\Handler::class // works fine with Company\Exceptions\Handler::class
);

// App/Exceptions/Handler.php
namespace App\Exceptions;

use Exception;

class Handler extends Company\Exceptions\Handler
{

}

// Company/Exceptions/Handler.php
namespace Company\Exceptions;

use Illuminate\Database\Eloquent\ModelNotFoundException;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Redirect, Request, Response, Session;
use Exception;

class Handler extends \GrahamCampbell\Exceptions\ExceptionHandler
{
    protected $dontReport = [
        \Symfony\Component\HttpKernel\Exception\HttpException::class,
        \Watson\Validating\ValidationException::class,
        ValidationException::class,
        ModelNotFoundException::class,
    ];

    public function render($request, Exception $e)
    {
        // ... //
        return parent::render($request, $e);
    }
}
```

I don't see anything there hence the fact that I need to replicate these handlers with a clean laravel app

**Comment by younes0** [comment]
Forgot to put a \ to `Handler extends \Company\Exceptions\Handler`
And since there was no log, I suggested that the fault wasn't mine :-1: 

Thanks for your time.
