### ISSUE TITLE
Able to configure placeholder 'Houston, We Have A Problem.' in InformationMerger or ability to override implementation

### ISSUE THREAD

**Issue by 4n70w4** [GrahamCampbell/Laravel-Exceptions#150]
Hi!

This is not a serious phrase and it would be nice to be able to change it for example via config or anyway.
Not everyone understands such a joke.

https://github.com/GrahamCampbell/Laravel-Exceptions/blob/0caee9f11559fa9aa8cfad048eb34bd4bc59915a/src/Information/InformationMerger.php#L39

https://github.com/GrahamCampbell/Laravel-Exceptions/blob/0caee9f11559fa9aa8cfad048eb34bd4bc59915a/src/Information/InformationMerger.php#L42

Calls are hardcoded and there is no way to redefine them:

https://github.com/GrahamCampbell/Laravel-Exceptions/blob/0caee9f11559fa9aa8cfad048eb34bd4bc59915a/src/Information/ArrayInformation.php#L61

https://github.com/GrahamCampbell/Laravel-Exceptions/blob/0caee9f11559fa9aa8cfad048eb34bd4bc59915a/src/Information/NullInformation.php#L43

Current need redeclare all of `InformationFactory`, `NullInformation`, `ArrayInformation` and `InformationMerger` for change 1 string value. A bit tricky for simple task.

**Comment by GrahamCampbell** [comment]
Thanks for the report, and I agree. I'll have a think about the best way to do this for version 15.0.0, and possibly change the default. Did you have anything in mind?

**Comment by GrahamCampbell** [comment]
Done in a4381458ec644d0404c0cce785849b8e9c252893.

**Comment by GrahamCampbell** [comment]
I've also decided to just remove the summary field.
