### ISSUE TITLE
Is it compatible with Laravel Nova?

### ISSUE THREAD

**Issue by jleei** [GrahamCampbell/Laravel-Exceptions#155]
Nova login page shows a 500 auth error. 

```
Laravel\Nova\Exceptions\AuthenticationException
```

**Comment by GrahamCampbell** [comment]
You'll need to implement an exception transformer for this. We don't natively support Nova. :)

**Comment by GrahamCampbell** [comment]
In your app code, you can copy (and edit, as required) https://github.com/GrahamCampbell/Laravel-Exceptions/blob/15.0/src/Transformer/AuthTransformer.php, then register your class in the config file.
