### ISSUE TITLE
Generate Unique Error Codes

### ISSUE THREAD

**Issue by GrahamCampbell** [GrahamCampbell/Laravel-Exceptions#16]
We should generate unique error codes and attach them to the logs, and present them to the user. That way if a user wants to contact support, they can provide us with the unique error code.

**Comment by GrahamCampbell** [comment]
This should be relatively easy to do actually. :)

**Comment by jbrooksuk** [comment]
Yes!

**Comment by GrahamCampbell** [comment]
I'll get this done later today.

**Comment by GrahamCampbell** [comment]
Done.

**Comment by TheAlexLichter** [comment]
@GrahamCampbell Is this feature meanwhile implemented in Laravel itself?

**Comment by GrahamCampbell** [comment]
No. The fact that this works in this package is a hack anyway.

**Comment by TheAlexLichter** [comment]
Ah, too bad. Such a feature would make debugging and fixing errors that users experience much easier.

Any chances that we see something like this in Laravel in the future?

**Comment by GrahamCampbell** [comment]
Unlikely tbh.

**Comment by GrahamCampbell** [comment]
It's already provided by this package though, so.

**Comment by GrahamCampbell** [comment]
https://github.com/GrahamCampbell/Laravel-Exceptions/blob/master/src/ExceptionIdentifier.php

**Comment by GrahamCampbell** [comment]
If you don't care about the id being a uuid, then just use `spl_object_hash`. It's already built into php.

**Comment by TheAlexLichter** [comment]
Yeah, you are right! 

I try to stay as independent as possible and therefore don't want to rely on many packages, that's why I asked. 

But thanks for linking the code and the advices! I'll check it out and think about an own implementation.

**Comment by GrahamCampbell** [comment]
> I try to stay as independent as possible and therefore don't want to rely on many packages

Well, Laravel already has a mountain of dependencies, so. :P

**Comment by TheAlexLichter** [comment]
Yeah.. that's a bit ironic :laughing:
