### ISSUE TITLE
Output error templates

### ISSUE THREAD

**Issue by antonkomarev** [GrahamCampbell/Laravel-Exceptions#23]
It will be great to have templates customizable via `config/exceptions.php`.

**ExceptionsServiceProvider.php**

```
$this->app->singleton(ExceptionInfo::class, function () {
    return new ExceptionInfo(__DIR__.'/../resources/errors.json');
});

$this->app->bind(HtmlDisplayer::class, function ($app) {
    return new HtmlDisplayer($app->make(ExceptionInfo::class), __DIR__.'/../resources/error.html');
});
```

Right now I need such things:
- Multi language error message for json output:

`./resources/views/errors/ru/error.json`
- Multi language error templates:

`./resources/views/errors/ru/error.html`
- Have different templates dependent of Exception:

`./resources/views/errors/ru/404.html` (if Exception don't have template - use default one).
- Application is separated on 2 parts: frontend & backend. Each of them got separate error templates for HtmlDisplayer (but I think this task is too complex and not so common to be included base package):

`./resources/views/frontend/errors/ru/404.html`

**Comment by GrahamCampbell** [comment]
All your multilanuage needs can be implement throw custom displayers.

**Comment by GrahamCampbell** [comment]
You can just return false in the canDisplay method if the language is not supported by each of your customer dispayers.

**Comment by GrahamCampbell** [comment]
> Application is separated on 2 parts: frontend & backend. Each of them got separate error templates for HtmlDisplayer (but I think this task is too complex and not so common to be included base package):

Again, you can do this with your own "canDisplay" logic.

**Comment by GrahamCampbell** [comment]
> It will be great to have templates customizable via config/exceptions.php.

So in summary, they are customizable.

**Comment by GrahamCampbell** [comment]
Example: https://styleci.io/123. That website uses this package and has custom error pages.
