### ISSUE TITLE
Exception handler only for Local?

### ISSUE THREAD

**Issue by Jaspur** [GrahamCampbell/Laravel-Exceptions#24]
Hi,

I wanna use your Whoops handler for Local development, and Bugsnag for production, but they both need the same changes in the Exceptions Handler.

```
use Exception;
#use Illuminate\Foundation\Exceptions\Handler as ExceptionHandler;
#use GrahamCampbell\Exceptions\ExceptionHandler as ExceptionHandler;
use Bugsnag\BugsnagLaravel\BugsnagExceptionHandler as ExceptionHandler;

class Handler extends ExceptionHandler {
```

Isn't there a way to use both?

This doesn't work of course :p

```
if(env('APP_ENV') == 'local')
{
    use GrahamCampbell\Exceptions\ExceptionHandler as ExceptionHandler;
}
else
{
    use Bugsnag\BugsnagLaravel\BugsnagExceptionHandler as ExceptionHandler;
}
```

**Comment by GrahamCampbell** [comment]
All you need to do is deal with this logic within the canDisplay method for your displayers.

**Comment by GrahamCampbell** [comment]
> use Bugsnag\BugsnagLaravel\BugsnagExceptionHandler as ExceptionHandler;

I'd recommend using my bugsnag package instead since there's is a bit crap imo.

My bugsnag package works by tuning into the logger instead of messing with the exception handler.

**Comment by GrahamCampbell** [comment]
https://github.com/AltThree/Bugsnag

**Comment by GrahamCampbell** [comment]
You'll need https://github.com/AltThree/Logger too. Then just add the bugsnag logger into https://github.com/AltThree/Logger/blob/master/config/logger.php.

**Comment by Jaspur** [comment]
Nice :+1: 
Installed it. What is the Bugsnag logger class to add to the logger config?

**Comment by vinkla** [comment]
``` php
'loggers' => [
    'Illuminate\Log\Writer' => ['*'],
    'AltThree\Bugsnag\Logger' => ['*'],
],
```

**Comment by Jaspur** [comment]
Thanks @vinkla !

@GrahamCampbell but now also all "local" stage errors are added to Bugsnag.
