### ISSUE TITLE
CSRF expired error code

### ISSUE THREAD

**Issue by antonkomarev** [GrahamCampbell/Laravel-Exceptions#25]
It's not an issue, it's a question. What was the reason to change default CSRF exception status code?

**Comment by GrahamCampbell** [comment]
Because bad request is more correct than internal server error.

**Comment by GrahamCampbell** [comment]
If you don't want that behaviour, that's fine, just disable that transformer in the config file. Aside from being useful imo, it's also there as an example of how to write a transformer. :)

**Comment by antonkomarev** [comment]
Yes, thanks a lot. I just thought to create separate error code, to make easier to take decisions from javascript. Because CSRF means that session is outdated and need to bypass user to login form.

**Comment by GrahamCampbell** [comment]
> Because CSRF means that session is outdated

Or it means that someone's trying to hack your users.
