### ISSUE TITLE
[Question] Access the reference id in blade template

### ISSUE THREAD

**Issue by Eloqex** [GrahamCampbell/Laravel-Exceptions#40]
I have currently got the package installed using error blade files from my errors folder, everything is working fine but I can't seem to access the {{ $id }} for the error reference. 

Is there anyway to access this from blade templates ? I have tried @{{ $id }} and just {{ $id }} but I'm not sure its even getting passed to them.

**Comment by GrahamCampbell** [comment]
That's because we don't pass any variables through.

https://github.com/GrahamCampbell/Laravel-Exceptions/blob/master/src/Displayers/ViewDisplayer.php#L56

**Comment by GrahamCampbell** [comment]
Laravel doesn't pass any variables through, so were were being consistent with them.

**Comment by GrahamCampbell** [comment]
@Eloqex Let me know if #41 does what you want?

**Comment by Eloqex** [comment]
That looks ace :)

**Comment by GrahamCampbell** [comment]
@Eloqex This feature will be available in v8.0.0 when I tag it. I had to bump the major version due to the breaking change made to the constructor, and, I guess, passing those variables through was also breaking as well as being a feature.
