### ISSUE TITLE
Illuminate\Contracts\Container\BindingResolutionException: Target [Illuminate\Contracts\Debug\ExceptionHandler] is not instantiable.

### ISSUE THREAD

**Issue by tkprocat** [GrahamCampbell/Laravel-Exceptions#42]
I was getting a "Illuminate\Contracts\Container\BindingResolutionException: Target [Illuminate\Contracts\Debug\ExceptionHandler] is not instantiable" error while running phpUnit under Laravel 5.2 and managed to replicate it on a new project with just Laravel-Exceptions. I tracked it down to possible a missing comment in the installation documentation.
It seems that, atleast on 5.2, you need to change the following in bootstrap\app.php

$app->singleton(
    Illuminate\Foundation\Exceptions\Handler::class,
    App\Exceptions\Handler::class
);

to 

$app->singleton(
    GrahamCampbell\Exceptions\ExceptionHandler::class,
    App\Exceptions\Handler::class
);

Does that seem right? And if so, could you please add it to the installation description to help others?

Funny enough the site worked fine, just the phpUnit that was complaining about it.

**Comment by vinkla** [comment]
It is the other way around:

``` php
$app->singleton(
    Illuminate\Foundation\Exceptions\Handler::class,
    GrahamCampbell\Exceptions\ExceptionHandler::class
);
```

**Comment by vinkla** [comment]
Please see https://github.com/StyleCI/StyleCI/blob/182b1546d86e63c1ece33c13226557455ed5d732/bootstrap/app.php#L42

**Comment by tkprocat** [comment]
So https://github.com/tkprocat/laravel-test-error/blob/master/bootstrap/app.php should be set up correctly? 
That is currently giving an error when running phpUnit on the it.

**Comment by GrahamCampbell** [comment]
I can't replicate. It must be something wrong in your app.

**Comment by GrahamCampbell** [comment]
Also, make sure you use phpunit 4, laravel isn't compatible with phpunit 5.

**Comment by tkprocat** [comment]
I'm running 4.8.21 under homestead.

Did you clone it and not get an error while running phpUnit?

**Comment by GrahamCampbell** [comment]
I use my own package in lots of projects both with phpunit 4 and 5, and it works just fine.

**Comment by GrahamCampbell** [comment]
Did you correctly install the package?

**Comment by GrahamCampbell** [comment]
You need to add the service provider near the top of the list of service providers, AND run `php artisan config:cache`, as needed every time you modify any config in laravel, AND run `php artisan optimize --force` to ensure your compiled.php file is up-to-date.

**Comment by tkprocat** [comment]
I tried your description above and it didn't help anything. Just to test that the package was installed correctly I made a dummy exception route and it shows the page with id and it gets logged. 

Just to be sure I've set things up correctly, can you give me a walkthrough of what needs to be changed on a freshly copy of laravel 5.2? Then I'll make a new project again tomorrow and remake the test to see if that helps.

**Comment by redgluten** [comment]
I’ve got this error on several Laravel 5.1 projects. I’ve followed every step suggested here, the service provider is the first called in the list and I’m using whoops 2.0 if it helps narrow the issue. Is there something else that could help you find the culprit?

It’s a great package by the way, thanks for the hard work. :+1:

**Comment by GrahamCampbell** [comment]
Did you make sure to run `php artisan config:cache`?

**Comment by redgluten** [comment]
Yes, I’ve ran every command listed here.

Here’s my list of providers minus those listed with the default Laravel install:

``` php
'providers' => [
        GrahamCampbell\Exceptions\ExceptionsServiceProvider::class,
        Collective\Html\HtmlServiceProvider::class,
        Intervention\Image\ImageServiceProvider::class,
        Mews\Purifier\PurifierServiceProvider::class,
        Maatwebsite\Excel\ExcelServiceProvider::class,
        Barryvdh\Debugbar\ServiceProvider::class,
        Spatie\LaravelAnalytics\LaravelAnalyticsServiceProvider::class,
]
```

My entire `app\Exceptions\Handler`:

``` php
<?php

namespace App\Exceptions;

use Exception;
use Illuminate\Database\Eloquent\ModelNotFoundException;
use Symfony\Component\HttpKernel\Exception\HttpException;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use GrahamCampbell\Exceptions\ExceptionHandler as ExceptionHandler;

class Handler extends ExceptionHandler
{
    /**
     * A list of the exception types that should not be reported.
     *
     * @var array
     */
    protected $dontReport = [
        HttpException::class,
        ModelNotFoundException::class,
    ];
    /**
     * Report or log an exception.
     *
     * This is a great spot to send exceptions to Sentry, Bugsnag, etc.
     *
     * @param  \Exception  $e
     * @return void
     */
    public function report(Exception $e)
    {
        return parent::report($e);
    }
    /**
     * Render an exception into an HTTP response.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Exception  $e
     * @return \Illuminate\Http\Response
     */
    public function render($request, Exception $e)
    {
        if ($e instanceof ModelNotFoundException) {
            $e = new NotFoundHttpException($e->getMessage(), $e);
        }
        return parent::render($request, $e);
    }
}
```

And my `composer.json` requires:

``` json
    "require": {
        "php": ">=5.5.9",
        "laravel/framework": "5.1.*",
        "laravelcollective/html": "~5.1",
        "intervention/image": "2.1.*",
        "maatwebsite/excel": "~2.0.0",
        "guzzlehttp/guzzle": "~5.0",
        "mews/purifier": "~2.0",
        "spatie/laravel-analytics": "^1.1",
        "league/csv": "^8.0"
    },
    "require-dev": {
        "graham-campbell/exceptions": "~8.1",
        "fzaninotto/faker": "~1.5",
        "mockery/mockery": "0.9.*",
        "phpunit/phpunit": "~4.0",
        "phpspec/phpspec": "~2.1",
        "barryvdh/laravel-debugbar": "^2.1"
    },
```

**Comment by GrahamCampbell** [comment]
> use GrahamCampbell\Exceptions\ExceptionHandler as ExceptionHandler;

You can drop the `as ExceptionHandler`.

> ```
>     "graham-campbell/exceptions": "~8.1",
> ```

This absolutely MUST NOT go into require-dev. It MUST go in `require`, however, you should add whoops in require dev.

**Comment by GrahamCampbell** [comment]
> ```
>     if ($e instanceof ModelNotFoundException) {
>         $e = new NotFoundHttpException($e->getMessage(), $e);
>     }
> ```

This code should be removed because this package already does that.

**Comment by GrahamCampbell** [comment]
Infact, you might as well just delete your exception handler, and bind ours in your bootstrap file.

**Comment by redgluten** [comment]
😑 Ok this is weird because I have many projects using your package and this is the only one where I made the mistake of putting it on the require-dev and forgot to add whoops.

So, my bad, but it doesn’t seems to be the issue here: it still gives me the error `Illuminate\Contracts\Container\BindingResolutionException: Target [Illuminate\Contracts\Debug\ExceptionHandler] is not instantiable.` when running phpunit.

Also: 

> ```
> if ($e instanceof ModelNotFoundException) {
>     $e = new NotFoundHttpException($e->getMessage(), $e);
> }
> ```
> 
> This code should be removed because this package already does that.

This is the [exact same code](https://github.com/laravel/laravel/blob/5.1/app/Exceptions/Handler.php) from the latest Laravel 5.1 branch. Maybe the readme should be updated then?

And:

> Infact, you might as well just delete your exception handler, and bind ours in your bootstrap file.

How should I do that exactly? Should I replace [this](https://github.com/laravel/laravel/blob/5.1/bootstrap/app.php) with this:

``` php
$app->singleton(
    GrahamCampbell\Exceptions\ExceptionsServiceProvider::class,
    App\Exceptions\Handler::class
);
```

**Comment by GrahamCampbell** [comment]
> How should I do that exactly? Should I replace this with this:

it's not working because you've setup the bindings wrong. You MUST leave the illuminate contract in.

**Comment by GrahamCampbell** [comment]
``` php
$app->singleton('Illuminate\Contracts\Debug\ExceptionHandler', 'GrahamCampbell\Exceptions\ExceptionHandler');
```

**Comment by redgluten** [comment]
I finally managed to make it work: it seems to be a problem with Phpunit versions: I had a global 5.2 phpunit while my project was using a 4.x version.

**Comment by mihailo-misic** [comment]
I had the same issue. _(Using Laravel 5.2)_
The problem was that i had a newer version of **phpunit** installed globally (5.4.4).
So by running **`phpunit`** command the global one was used.

Solutions:
1. Use **`./vendor/bin/phpunit`** instead;
2. Downgrade the global **phpunit**, after which you can use the **`phpunit`** command regularly.

```
composer global remove phpunit/phpunit
composer global require 'phpunit/phpunit=~4.0'
```

Or just don't globally require PHPUnit. 

Hope somebody finds this useful.

**Comment by DongJianWei24** [comment]
@mihailomisic useful ! think you
