### ISSUE TITLE
All non `HttpExceptionInterface` exceptions transformed to 500's?

### ISSUE THREAD

**Issue by hailwood** [GrahamCampbell/Laravel-Exceptions#43]
So I'm finding that this package is causing a bit of grief with the exceptions.

Let's say I make an API request to get a resource, but my app denies the request through laravels ACL, this throws a AuthorizationException which does not implement the `HttpExceptionInterface` Interface.

Laravel doesn't add a code to this exception(it really should be a 401 or 403) so I wrote a transformer that returns the exception but with a 401 code.

The issue is that because it doesn't implement `HttpExceptionInterface` when this package uses Symfony's FlattenException the status code gets reset to 500 which is annoying, but manageable.

The real issue then comes in when we hit ExceptionInfo::generate
because again we don't Implement `HttpExceptionInterface` we end up with the generic information from the json file.

So by the time the user get's the error they see
![selection_040](https://cloud.githubusercontent.com/assets/709773/12160350/f2156268-b54f-11e5-89f7-fc7d19f2068e.png)

So basic question, why are we so reliant on `HttpExceptionInterface`?

**Comment by GrahamCampbell** [comment]
This is the correct behaviour. You need to make an exception "transformer".

**Comment by GrahamCampbell** [comment]
> So basic question, why are we so reliant on HttpExceptionInterface?

Not the interface really, just the whole http exception thing from symfony.

**Comment by GrahamCampbell** [comment]
You are not expected to implement that interface yourself with your exceptions, infact I'd not recommend it at all.

**Comment by GrahamCampbell** [comment]
See how we have https://github.com/GrahamCampbell/Laravel-Exceptions/blob/master/src/Transformers/CsrfTransformer.php. You'd need to write something similar for `AuthorizationException`.

**Comment by GrahamCampbell** [comment]
Though, actually, since this exception is in laravel's core, I guess I could add this transformer to the core.

**Comment by GrahamCampbell** [comment]
> So basic question, why are we so reliant on HttpExceptionInterface?

That's more a security concern too. We don't want to just blab exceptions details to the user. Only actual http exceptions should be considered safe.

**Comment by hailwood** [comment]
@GrahamCampbell makes sense to me, also, lightning quick response!

``` php
<?php
namespace App\Exceptions\Transformers;

use Exception;
use GrahamCampbell\Exceptions\Transformers\TransformerInterface;
use Illuminate\Auth\Access\AuthorizationException;
use Symfony\Component\HttpKernel\Exception\HttpException;

class AuthorizationExceptionTransformer implements TransformerInterface
{
    /**
     * Transform the provided exception.
     *
     * @param \Exception $exception
     *
     * @return \Exception
     */
    public function transform(Exception $exception)
    {
        if ($exception instanceof AuthorizationException) {
            return new HttpException(401, $exception->getMessage(), $exception);
        }

        return $exception;
    }
}
```

**Comment by GrahamCampbell** [comment]
I'm actually about to add this right into this package with tests. ;)

**Comment by GrahamCampbell** [comment]
Don't we want http status 403 though, actually?

**Comment by hailwood** [comment]
Hmm yeah let's go with 403,

**Comment by GrahamCampbell** [comment]
Just checked and that's what laravel 5.2's exception handler would have done.

**Comment by GrahamCampbell** [comment]
See https://github.com/GrahamCampbell/Laravel-Exceptions/pull/44.

**Comment by GrahamCampbell** [comment]
This will be available in `v8.1.0` and greater.

**Comment by hailwood** [comment]
Sweet, I see you've merged it in, any idea when 8.1 will be released?
If it's gonna be a while then I'll just dev-master it heh.

**Comment by GrahamCampbell** [comment]
I've just released it. ;)

**Comment by GrahamCampbell** [comment]
Also, there's never any need to use `dev-master`.  You could have just used `8.1.*@dev` or `^8.1@dev`.

**Comment by hailwood** [comment]
Working like a charm. Much appreciated!
