### ISSUE TITLE
Use with bugsnag

### ISSUE THREAD

**Issue by simplenotezy** [GrahamCampbell/Laravel-Exceptions#45]
I am using bugsnag for my applications which means my handler.php is extending "Bugsnag\BugsnagLaravel\BugsnagExceptionHandler".

How can I use this package with bugsnag?

**Comment by vinkla** [comment]
Try using it with https://github.com/AltThree/Bugsnag instead of Bugsnag's own package. I'm currently using it in a project of mine and it works great.

**Comment by simplenotezy** [comment]
I see @vinkla , so you don't need to extend the error handler?

**Comment by vinkla** [comment]
I'm not sure what you mean?

**Comment by GrahamCampbell** [comment]
> I see @vinkla , so you don't need to extend the error handler?

No, just rebind the logger.

**Comment by simplenotezy** [comment]
@GrahamCampbell can you elaborate?

**Comment by k1ng440** [comment]
```
    public function report(Exception $e)
    {
        parent::report($e);
        app('bugsnag')->notifyException($e, []);

    }
```

**Comment by GrahamCampbell** [comment]
@k1ng440 No! Not at all!

**Comment by GrahamCampbell** [comment]
> No, just rebind the logger.

Bind the psr logging interface to the bugsnag logger from the alt-three package. That way you can actually have proper logging instead of this shitty hack.

**Comment by MikeElghali** [comment]
Hi,

@GrahamCampbell i use bugsnag-laravel and laravel-exception too. How i can do to report exception to Bugsnag ?

Actually, exceptions are stored only in log files and they aren't send to bugsnag.

Thanks

Regards.

**Comment by GrahamCampbell** [comment]
Bugsnag overloads the logging. Do nothing with the exception handler in order to use bugsnag. Just follow the setup docs for Bugsnag.

**Comment by GrahamCampbell** [comment]
NB This is with the new bugsnag library.

**Comment by MikeElghali** [comment]
Hi,

Thanks for response, if i understand, i need to remove laravel-exception package and only use bugsnag-laravel ?

EDIT : Handler class actually extends GrahamCampbell\Exceptions\ExceptionHandler. Is correct ?

Regards.

**Comment by GrahamCampbell** [comment]
> i need to remove laravel-exception package and only use bugsnag-laravel ?

No, you can use both.

**Comment by GrahamCampbell** [comment]
The new bugsnag library doesn't have an exception handler. It doesn't need one.
