### ISSUE TITLE
Whoops

### ISSUE THREAD

**Issue by simplenotezy** [GrahamCampbell/Laravel-Exceptions#46]
I am trying to install this project for my app, but I am not interested in the exceptions handler. Only the Whoops extension.

Can I install this package, and not having to worry about exceptions being thrown differently across my application?

**Comment by vinkla** [comment]
Then you should look see https://mattstauffer.co/blog/bringing-whoops-back-to-laravel-5

**Comment by GrahamCampbell** [comment]
This package doesn't change that behaviour and can be safely used out of the box.
