### ISSUE TITLE
White blank page if debug if false + Does not report to BugSnag

### ISSUE THREAD

**Issue by simplenotezy** [GrahamCampbell/Laravel-Exceptions#47]
I am visiting a page, and all I get is a blank page.

I check bugsnag and nothing is there.

I have filled out my bugsnag api code.

Unable how to debug further.

I am also using your Logging package.

```
'loggers' => env('APP_DEBUG', false) ? ['Illuminate\Log\Writer' => ['*']] : [
    'AltThree\Bugsnag\Logger'   => ['error', 'critical', 'alert', 'emergency'],
    'AltThree\Logify\Logger'    => ['*']
],
```

I figured out it only happens if APP_DEBUG is false.

**Comment by GrahamCampbell** [comment]
Unrelated to this package.
