### ISSUE TITLE
404 pages gone

### ISSUE THREAD

**Issue by simplenotezy** [GrahamCampbell/Laravel-Exceptions#48]
After installing this package, our 404 pages is gone. All we get is a white page on errors.

I guess it must be the same with 503, 500, etc. This is not so good, as it is running production.

**Comment by vinkla** [comment]
We've no idea how you've setup the package and we can't help you unless we get more information. Please **always** provide more information when creating issues. Just saying something doesn't work wont help anyone. Don't push broken stuff into production. Always test it first.

**Comment by simplenotezy** [comment]
All I've done is the default installation process. Have not changed config.

In `bootstrap/app.php` this is how I call your exceptionhandler

```
$app->singleton(
    'Illuminate\Contracts\Debug\ExceptionHandler',
    'GrahamCampbell\Exceptions\ExceptionHandler'
);
```

I use logger also. This is the logger configuration:

```
<?php

/*
 * This file is part of Alt Three Logger.
 *
 * (c) Alt Three Services Limited
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

return [

    /*
    |--------------------------------------------------------------------------
    | Loggers
    |--------------------------------------------------------------------------
    |
    | Here are each of the loggers to call under the hood while logging.
    |
    */

    'loggers' => env('APP_DEBUG', false) ? ['Illuminate\Log\Writer' => ['*']] : [
        'AltThree\Bugsnag\Logger'   => ['error', 'critical', 'alert', 'emergency'],
        'AltThree\Logify\Logger'    => ['*']
    ],

];
```

**Comment by simplenotezy** [comment]
This issue only happens if debug is set to `false`. If debug is `true` I get the usual error screen:

```
No query results for model [App\Company].
```

**Comment by vinkla** [comment]
Did you add the service provider?

**Comment by simplenotezy** [comment]
Yes I did

**Comment by GrahamCampbell** [comment]
Looks like it's a bug in your own error code then.

**Comment by simplenotezy** [comment]
How is that possible? I don't even use the native ErrorHandler; I use the error handler of this package.

```
 $app->singleton(
     'Illuminate\Contracts\Debug\ExceptionHandler',
     'GrahamCampbell\Exceptions\ExceptionHandler'
 );
```

It is defiantly confirmed that app throws a 404, or 500, but the package does not throw view views/CODE.blade.php as it should do.

**Comment by simplenotezy** [comment]
If I revert back to using:

```
'App\Exceptions\Handler'
```

404 pages are shown just fine.
