### ISSUE TITLE
Duplicate Content-Type Headers Causing Apache Error?

### ISSUE THREAD

**Issue by frasmage** [GrahamCampbell/Laravel-Exceptions#51]
Installed Laravel-Exceptions with Whoops on a project. Threw an exception to test and was surprised to be greeted by a generic server-generated 500 error page instead of whoops. My apache logs (using MAMP) indicated that duplicate 'Content-Type' were causing an error. I inspected the response return by the `GrahamCampbell\Exceptions\ExceptionHandler::render()` method and noticed that it specified `Content-Type: text/html` where as Illuminate's handler did not. 

I'm not sure where the content type is being inserted after the Handler does its thing, but this duplicate is clearly causing an issue. I was able to remedy the situation by doing the following, but a more permanent fix might be better.

```
public function render($request, Exception $e)
{
    if ($e instanceof ModelNotFoundException) {
        $e = new NotFoundHttpException($e->getMessage(), $e);
    }
    $response = parent::render($request, $e);
    $response->headers->remove('Content-Type');
    return $response;
}
```

**Comment by GrahamCampbell** [comment]
That fix you have, and actually the `if ($e instanceof ModelNotFoundException) {` thing is wrong.

**Comment by GrahamCampbell** [comment]
The correct way to do the `if ($e instanceof ModelNotFoundException) {` thing is by writing an exception transformer.

**Comment by GrahamCampbell** [comment]
In terms of the duplicate content type issue, there is no way you should be removing it like that.

**Comment by GrahamCampbell** [comment]
What exception is causing the issue for you?

**Comment by GrahamCampbell** [comment]
https://github.com/GrahamCampbell/Laravel-Exceptions/blob/master/src/Displayers/DebugDisplayer.php#L40

**Comment by GrahamCampbell** [comment]
I'm suspecting it's a case sensitivity issue in here.

**Comment by frasmage** [comment]
> That fix you have, and actually the if ($e instanceof ModelNotFoundException) { thing is wrong.

That was from the Laravel install, I didn't touch that piece of code, though I understand that transformer would be better.

> In terms of the duplicate content type issue, there is no way you should be removing it like that.

Just a quick-fix solution to prove the theory. I wouldn't leave that in production.

> What exception is causing the issue for you?

just a dummy exception for the sake of testing

```
Route::get('/', function(){ throw new \Exception('testing'); });
```

> I'm suspecting it's a case sensitivity issue in here.

You might be right. The apache error that I am getting mentions 'Content-type' with a lowercase "t". 

```
[Wed Jan 20 11:32:00 2016] [error] [client ::1] FastCGI: comm with server ".../MAMP/fcgi-bin/php5.6.10.fcgi" aborted: error parsing headers: duplicate header 'Content-type', referer: ...
```

I can't seem to find where that would be inserted, however. I only see that casing in some Monolog connectors. `Symfony\Component\HttpFoundation\Response::prepare()` appears to set the Content-Type headers. In any case the Symfony HeaderBag lowercases all keys.

**Comment by GrahamCampbell** [comment]
Surely it's impossible for this package to be causing duplicate headers then?

**Comment by frasmage** [comment]
Probably. Though what is the reason for setting the content-type explicitly rather than letting it be set automatically? The Illuminate exception renderer does not set a header.

**Comment by GrahamCampbell** [comment]
> Though what is the reason for setting the content-type explicitly rather than letting it be set automatically?

Because there's no reason to assume that our responses are html, infact, they;re not all html.

**Comment by GrahamCampbell** [comment]
If the browser says it only accepts json, then we return a json response. Basically, we respect the http accept header.

**Comment by GrahamCampbell** [comment]
For example:

![image](https://cloud.githubusercontent.com/assets/2829600/12461162/535d64f8-bfaf-11e5-9af1-ad2d7bd39fdc.png)

![image](https://cloud.githubusercontent.com/assets/2829600/12461173/63008c78-bfaf-11e5-8cab-a6e89e960c25.png)

**Comment by frasmage** [comment]
Alright, this might probably has nothing to do with this package. I confirmed that there is only one instance of the header at the point headers are being sent. This must be an issue in fCGI.

**Comment by frasmage** [comment]
Confirmed it has something to do with fCGI, running MAMP in module mode does not produce this issue. 

Sorry to bother you! Thanks for your help.

**Comment by GrahamCampbell** [comment]
No problem. ;)

**Comment by maxmirazh33** [comment]
@frasmage, do you have solution of this issue except use MAMP in module mode? Need to use CGI mode and this issue very annoying.
