### ISSUE TITLE
contentType seems to be ignroed.

### ISSUE THREAD

**Issue by k1ng440** [GrahamCampbell/Laravel-Exceptions#54]
HtmlDisplayer is being served even the content type is Accept:application/json, text/javascript, _/_; q=0.01

```
public function contentType() {
      return 'text/html';
}
```

**Comment by GrahamCampbell** [comment]
It's because your accept header is invalid.

**Comment by GrahamCampbell** [comment]
`/` is invalid syntax by itself.

**Comment by GrahamCampbell** [comment]
Oh, wait, I see - you've not formatted the code so github can render it correctly.

**Comment by GrahamCampbell** [comment]
That said, your bug report is invalid, because the tests prove that this does work.

**Comment by GrahamCampbell** [comment]
https://github.com/GrahamCampbell/Laravel-Exceptions/blob/master/tests/ExceptionHandlerTest.php#L112

**Comment by GrahamCampbell** [comment]
The `*/*` in your accept header tells us that your client can accept any content type, so the server chooses its preferred content type, according to the order defined in the config file for this package. The http spec doesn't require the server to be forced to use the client's first choice - it only has to select a content type the client claimed to understand. If you don't want html, don't say that it's acceptable to the server, and it won't give you html back.

**Comment by k1ng440** [comment]
well then how i prevent the browser from sending 10 `*/*` when requesting with xhr requests?

is there anyway you can make  `*/*` low priority?

**Comment by GrahamCampbell** [comment]
> well then how i prevent the browser from sending 10 _/_ when requesting with xhr requests?

Quite easily. This issue isn't the place for that though.
