### ISSUE TITLE
inserting `'editor'=>'phpstrom'` in \config\exceptions.php has no effect. 

### ISSUE THREAD

**Issue by salarmehr** [GrahamCampbell/Laravel-Exceptions#55]
I tied to set default editor: https://github.com/filp/whoops/blob/master/docs/Open%20Files%20In%20An%20Editor.md

inserting `'editor'=>'phpstrom'` in \config\exceptions.php has no effect.

**Comment by GrahamCampbell** [comment]
> inserting 'editor'=>'phpstrom' in \config\exceptions.php has no effect.

Yes, that config file has nothing to do with whoops.

**Comment by GrahamCampbell** [comment]
You should probably extend https://github.com/GrahamCampbell/Laravel-Exceptions/blob/master/src/Displayers/DebugDisplayer.php#L48 and overwrite that method.

**Comment by salarmehr** [comment]
I am a little reluctant to use this package anymore. It returns white screen sometimes.
For example when the path of a view is invalid.

**Comment by GrahamCampbell** [comment]
That's surely nothing unique to this package. Laravel will suffer the same issue since I just lifted the code from laravel for the view displayer?
