### ISSUE TITLE
Unit testing; Error: Call to undefined method Illuminate\Http\Response::getTargetUrl()

### ISSUE THREAD

**Issue by stefro** [GrahamCampbell/Laravel-Exceptions#57]
Hi,

I had a strange problem in Phpunit that I couldn't relate to this package at first. 
As soon as I dissabled this package everything worked just fine. Here is some additional info: https://laracasts.com/discuss/channels/laravel/unit-testing-error-call-to-undefined-method-illuminatehttpresponsegettargeturl

**Comment by GrahamCampbell** [comment]
`getTargetUrl()` doesn't appear anywhere in this code base?

**Comment by GrahamCampbell** [comment]
It only appears in `Illuminate\Foundation\Testing\Concerns\InteractsWithPages::followRedirects()`. It looks to me like you have a bad middleware somewhere causing this.

**Comment by GrahamCampbell** [comment]
Unrelated to this package.

**Comment by redgluten** [comment]
I got the same problem randomly appearing on this test:

``` php
/** @test */
function create_new_article()
{
    $admin   = $this->getAdminUser();
    $article = factory(App\Article::class)->make();
    $this->actingAs($admin)
         ->visit(route('admin.article.create'))
         ->seePageIs('/admin/article/create')
         ->see('Nouvel article')
         ->type($article->title, 'title')
         ->type($article->chapeau, 'chapeau')
         ->type($article->content, 'content')
         ->select($article->issue_id, 'issue_id')
         ->press('Enregistrer')
         ->see('L’article ' . $article->title . ' a bien été créé');
}
```

I only have the default middlewares, I am using v8.6.1 of this package and Laravel v5.2.39.

**Comment by GrahamCampbell** [comment]
As I said, this is unrelated to this package?
