### ISSUE TITLE
Blade-based error pages with Blade directives or PHP code cause a default 500 Internal Server Error page to appear

### ISSUE THREAD

**Issue by mseymour** [GrahamCampbell/Laravel-Exceptions#58]
Versions: Laravel 5.2, Laravel-Exceptions 8.4

If I try to invoke an error page that I have as a blade template that contains PHP or Blade directives (errors/404.blade.php), I get this error:

```
[2016-04-27 16:53:08] local.CRITICAL: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Method Illuminate\View\View::__toString() must not throw an exception' in [...]/bootstrap/cache/compiled.php:0
Stack trace:
#0 {main} {"identification":{"id":"eeafdb97-45bb-495c-90cc-5c0f2a41790e"}}
```

Presumably the error page isn't actually being rendered and is instead being cast to `String`.

**Comment by GrahamCampbell** [comment]
Looks like your error pages are broken.

**Comment by mseymour** [comment]
Nope. No matter what code I put in the view, it breaks. PHP is trying to cast the View object to a string, when View::render() should be called.

I don't think there's anything wrong with the render() method under App\Exceptions\Handler:

public function render($request, Exception $e) { return parent::render($request, $e); }

Sent from my iPhone

**Comment by GrahamCampbell** [comment]
> PHP is trying to cast the View object to a string, when View::render() should be called.

No, that is not true, and it is not what the exception message is telling you.

**Comment by mseymour** [comment]
Weird. I was trying to see what variables were available to me with `{{ dd(get_defined_vars() }}` and it was throwing an exception. Probably something that I missed from when I was using something else with the error pages. My bad.
