### ISSUE TITLE
Incorrectly handles the error 404

### ISSUE THREAD

**Issue by andrey-helldar** [GrahamCampbell/Laravel-Exceptions#59]
In Laravel code using the method `DB::whereSlug($slug)->firstOrFail()`, which in the absence of the data automatically returns a 404 error and redirect it to the page.

Package an error Whoops:

> Symfony\Component\HttpKernel\Exception\NotFoundHttpException thrown with message "No query results for model [App\News]."
> 
> \vendor\graham-campbell\exceptions\src\Transformers\ModelTransformer.php
> 
> public function transform(Exception $exception)
>     {
>         if ($exception instanceof ModelNotFoundException) {
>             $message = $exception->getMessage();
>             $exception = new NotFoundHttpException($message ?: null);
>         }
> 
> ```
>     return $exception;
> }
> ```

I use default configuration, as in the documentation have not found how to customize the processing of certain error codes.

If you disable the debug mode, the redirection to the error page runs normally.

(Translated by Google Translate)

**Comment by GrahamCampbell** [comment]
I don't see an error there? Showing whoops is the correct behaviour if you're in debug mode.

**Comment by andrey-helldar** [comment]
[pic 1: in debug mode](http://savepic.ru/9748219.jpg)
[pic 2: in production mode](http://savepic.ru/9727739.jpg)

It must be like this:
[Debug mode with error code 500](http://savepic.ru/9708282.jpg)
[Debug mode with error code 404](http://savepic.ru/9707258.jpg)

Maybe, need to configure the package for the job?

P.S.: I using [Laravel 5.2 Eloquent (Retrieving Single Models / Aggregates)](https://laravel.com/docs/5.2/eloquent#retrieving-single-models):

> Not Found Exceptions
> Sometimes you may wish to throw an exception if a model is not found. This is particularly useful in routes or controllers. The `findOrFail` and `firstOrFail` methods will retrieve the first result of the query. If the exception is not caught, a 404 HTTP response is automatically sent back to the user, so it is not necessary to write explicit checks to return 404 responses when using these methods:
> Route::get('/api/flights/{id}', function ($id) {
>     return App\Flight::findOrFail($id);
> });

**Comment by GrahamCampbell** [comment]
It's not actually an error 500. Look at the http code. It's a 404 whoops page.

**Comment by andrey-helldar** [comment]
Hm... Definitely!
Thanks!)

**NotFoundHttpException** == 404 Not Found :)
