### ISSUE TITLE
Allow to modify Whoops Handler in DebugDisplayer

### ISSUE THREAD

**Issue by borys-p** [GrahamCampbell/Laravel-Exceptions#62]
I'd like to use the nice Whoops feature that allows to open the specified file directly in the editor. It requires calling setEditor() on the Handler object. Unfortunately this object can't be accessed outside of the package. Extending DebugDisplayer.php will be messy and will break updates. How about an extra config option or some other way to modify this handler?

**Comment by vinkla** [comment]
You could extend the DebugDisplayer class and replace it in the configuration file. If you haven't specified `dev-master` in your composer file, I think you will be fine. @GrahamCampbell always follow SemVer.

**Comment by GrahamCampbell** [comment]
Yes, you can simply extend my displayers and update your exception.php config file. That's why I wrote it like this.
