### ISSUE TITLE
ViewDisplayer doesn't use the current route middleware group

### ISSUE THREAD

**Issue by williammck** [GrahamCampbell/Laravel-Exceptions#63]
Not sure how feasible it would be to implement this, but if a request came in from the "web" (default) middleware group I'd love to see all the middleware for that still apply.

If there's an easy way to do this that I'm just missing, I can also take a look at the code and get it to work.

Thanks!

**Comment by GrahamCampbell** [comment]
That should still happen. In laravel, 5.2, whenever you throw the exception, the application still exists through the middleware. This does not happen in 5.1 though for BC reasons.

**Comment by williammck** [comment]
Now that I look at it more, it seems to only be happening on 404 errors where a route doesn't exist (abort(404) works fine) - therefore outside middleware.

**Comment by GrahamCampbell** [comment]
Right, yeh. This is probably due to where your middlewares are. Only the global ones will get run if no routes are matched.
