### ISSUE TITLE
Maintenance mode, php artisan down, throws an exception

### ISSUE THREAD

**Issue by bridgeport** [GrahamCampbell/Laravel-Exceptions#64]
Hi Graham,

Thanks for this great package.

I'm using Exceptions v8.6.1 and Laravel 5.2.39

When I run "php artisan down" an exception is thrown:

whoops outputs:

```
Symfony\Component\HttpKernel\Exception\HttpException 
...\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode.php:41
```

``` php
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @return mixed
     *
     * @throws \Symfony\Component\HttpKernel\Exception\HttpException
     */
    public function handle($request, Closure $next)
    {
        if ($this->app->isDownForMaintenance()) {
            throw new HttpException(503);
        }

        return $next($request);
    }
}
```

This maintenance page shows fine when Laravel-Exceptions is not installed.

Thanks.

**Comment by GrahamCampbell** [comment]
This is the correct behaviour. Turn debug mode off to see your maintenance screen. Our debug mode means that you get to see the whoops page for all exceptions.

**Comment by GrahamCampbell** [comment]
Note that the whoops screen still is a down for maintenance page. The HTTP status code will still be 503.

**Comment by bridgeport** [comment]
Thanks for clarifying Graham.

**Comment by GrahamCampbell** [comment]
No problem. If you don't want the whoops screen for 503 pages, you can extend my whoops displayer, and modify the shouldDisplay function. :)

**Comment by GrahamCampbell** [comment]
That's why i have configuration files that support changing what displayers are used, so people can easily customize things to their exact liking.
