### ISSUE TITLE
Identification Id is not passed to Monolog

### ISSUE THREAD

**Issue by majksner** [GrahamCampbell/Laravel-Exceptions#65]
Hi,

It seems identification is not passed correctly to monolog for logging, I believe issue is at `ExceptionHandlerTrait`. 

https://github.com/GrahamCampbell/Laravel-Exceptions/blob/master/src/ExceptionHandlerTrait.php#L63

If I change that line from:
`$logger->{$level}($e, ['identification' => ['id' => $id]]);`
to
`$logger->{$level}($e, ['identification' => $id]);`

Everything works as expected and identification gets passed to monolog.

**Comment by GrahamCampbell** [comment]
Monolog must be using a different kind of id system. This was never intended to map to that.
