### ISSUE TITLE
AuthenticationException not calling unauthenticated() method

### ISSUE THREAD

**Issue by Muffinman** [GrahamCampbell/Laravel-Exceptions#68]
Hi,

The default Laravel 5.3 error handler calls the `unauthenticated()` method when the error thrown is an instance of `AuthenticationException`. You can see this in https://github.com/laravel/framework/blob/5.3/src/Illuminate/Foundation/Exceptions/Handler.php#L133

Is there a specific reason that this method doesn't fire when using the `NewExceptionHander`? Is there a better way to redirect to a login page if the request is not authenticated?

The current way this is working means that the `unauthenticated()` method in `App\Exceptions\Handler.php` will never fire. Does this mean we need to be detecting the instance type and handling this ourselves in `App\Exceptions\Hander::render()` ?

```
    /**
     * Convert an authentication exception into an unauthenticated response.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Illuminate\Auth\AuthenticationException  $e
     * @return \Illuminate\Http\Response
     */
    protected function unauthenticated($request, AuthenticationException $e)
    {
        if ($request->expectsJson()) {
            return response()->json(['error' => 'Unauthenticated.'], 401);
        } else {
            return redirect()->guest('login');
        }
    }
```

**Comment by GrahamCampbell** [comment]
Thanks for getting in touch. This won't work the same as the default laravel exception handler, and I don't recommend you override the render method. Instead, I'd recommend you create a "displayer" and allow that to handle what you want. In this case, you might want two displayers, for each branch in that if.

**Comment by Muffinman** [comment]
Hi Graham, thanks for the reply. I can see what you're saying and yes that does make sense.

The only issue is that I always want this redirect to be in place, whether it's called from `HtmlDisplayer` / `DebugDisplay` etc. It should really happen at a level above this.

Perhaps It could be done as a `filter` instead?

P.S. I don't think it will make any difference to the logic but I'm using flip/whoops as the debug displayer.

EDIT: For my purpose I may just leave the redirect logic in my exceptions handler `render()` method. If and when we upgrade this to a newer version of Laravel we'll more than likely have to update this file anyway.

**Comment by GrahamCampbell** [comment]
You can place the redirect displayer above the debug and html ones in the config file to give it priority.

**Comment by tucq88** [comment]
Try to write an CustomDisplayer but don't see it worked. @GrahamCampbell  Could you give me an example about building a customdisplayer so I could manage to do it myself ?

**Comment by GrahamCampbell** [comment]
Just look at the ones in this package. :)

**Comment by g87andres** [comment]
I used the following for my custom displayer, which works:

`<?php

namespace App\Exceptions;

use Exception;
use GrahamCampbell\Exceptions\Displayers\DisplayerInterface;


class AuthenticationExceptionDisplayer implements DisplayerInterface
{
	/**
	 * Get the error response associated with the given exception.
	 *
	 * @param \Exception $exception
	 * @param string     $id
	 * @param int        $code
	 * @param string[]   $headers
	 *
	 * @return \Symfony\Component\HttpFoundation\Response
	 */
	public function display(Exception $exception, $id, $code, array $headers)
	{
		if (\Request::expectsJson()) {
			return response()->json(['error' => 'Unauthenticated.'], 401);
		}
		
		return redirect()->guest('login');
		
	}
	
	/**
	 * Get the supported content type.
	 *
	 * @return string
	 */
	public function contentType()
	{
		return 'text/html';
	}
	
	/**
	 * Can we display the exception?
	 *
	 * @param \Exception $original
	 * @param \Exception $transformed
	 * @param int        $code
	 *
	 * @return bool
	 */
	public function canDisplay(Exception $original, Exception $transformed, $code)
	{
		return true;
	}
	
	/**
	 * Do we provide verbose information about the exception?
	 *
	 * @return bool
	 */
	public function isVerbose()
	{
		return true;
	}
}
`

**Comment by tucq88** [comment]
lol if I could find anything I would not asking  you like this

**Comment by GrahamCampbell** [comment]
https://github.com/GrahamCampbell/Laravel-Exceptions/tree/master/src/Displayers

**Comment by Sameerpraz** [comment]
i am having the same problem
