### ISSUE TITLE
Proposal Custom Displayers

### ISSUE THREAD

**Issue by vinkla** [GrahamCampbell/Laravel-Exceptions#7]
I would really like to see custom displayers and the ability to customize the existing ones. My idea is to create a configuration file with all displayers that should be loaded as well as a default one. The configuration file would look something like to this:

``` php
/*
|--------------------------------------------------------------------------
| Default Exception Displayer
|--------------------------------------------------------------------------
|
| Here you may specify which of the exception displayers below you wish to
| use as your default displayer for all exceptions.
|
*/

'default' => 'plain',

/*
|--------------------------------------------------------------------------
| Exception Displayers
|--------------------------------------------------------------------------
|
| Here are each of the exception displayers setup for your application.
| Default displayers has been included, but you may add as many displayers
| as you would like.
|
*/

'displayers' => [
    'array' => 'GrahamCampbell\Exceptions\Displayers\ArrayDisplayer',
    'debug' => 'GrahamCampbell\Exceptions\Displayers\DebugDisplayer',
    'plain' => 'GrahamCampbell\Exceptions\Displayers\PlainDisplayer',
],
```

Each displayer class should have a class that we can call to determine if this displayer should be used or not. Currently named it `use`, there probably is a much better name.

``` php
/**
 * This is the array displayer class.
 *
 * @author Graham Campbell <graham@mineuk.com>
 */
class ArrayDisplayer implements DisplayerInterface
{
    /**
     * Get the content associated with the given exception.
     *
     * @param \Exception $exception
     * @param int        $code
     *
     * @return array
     */
    public function display(Exception $exception, $code)
    {
        $info = ExceptionInfo::generate($code, $exception->getMessage());

        return ['success' => false, 'code' => $info['code'], 'msg' => $info['extra']];
    }

    /**
     * The method to decide if this displayer should be used or not.
     *
     * @param \Exception               $exception
     * @param \Illuminate\Http\Request $request
     *
     * @return bool
     */
    public function use(Exception $exception, Request $request)
    {
        return $request->ajax();
    }
}
```

Then at last the `getContent` method in the `ExceptionHandler` class loops over the displayers specified in the configuration file and then sees which one to use. In this way we won't break any current setup. You wont have to publish the configuration if you don't want to.

What do you think @GrahamCampbell? Is this solution too complex?

**Comment by GrahamCampbell** [comment]
> What do you think @GrahamCampbell? Is this to complex?

No, I think that looks ok. :)

**Comment by vinkla** [comment]
Awesome! Then I'll try to work something out. Soon available in a pull request near you :)

**Comment by GrahamCampbell** [comment]
:beers:

**Comment by GrahamCampbell** [comment]
Maybe instead of `use`, `canDisplay`, or `shouldDisplay`?

**Comment by vinkla** [comment]
Yeah, I think `shouldDisplay` sounds good.

**Comment by GrahamCampbell** [comment]
In auto-presenter, we use `decorate` and `canDecorate` fyi. https://github.com/laravel-auto-presenter/laravel-auto-presenter/blob/master/src/Decorators/CollectionDecorator.php#L28

**Comment by vinkla** [comment]
I'll update to `canDisplay` then. How should we handle the default displayer? I mean the `canDisplay` method will always return true for `PlainDisplayer`.

**Comment by GrahamCampbell** [comment]
We need a getPriority method then. That way we can cycle through all available displayers and get a prioritised list of displayers that say they can display the content.

**Comment by GrahamCampbell** [comment]
How does that sound?

**Comment by GrahamCampbell** [comment]
If you like, I can write that bit after you're done.

**Comment by vinkla** [comment]
Please see #8.
