### ISSUE TITLE
Whoops page when AuthenticationException is thrown in laravel 5.3

### ISSUE THREAD

**Issue by scrubmx** [GrahamCampbell/Laravel-Exceptions#80]
There is an issue with new laravel 5.3 apps.

The new auth middleware `Illuminate\Auth\Middleware\Authenticate` throws an `AuthenticationException` when the user is not logged in. The default exception handler handles this by calling the `unauthenticated` method in the `App\Exceptions\Handler`.

https://github.com/laravel/framework/blob/5.3/src/Illuminate/Foundation/Exceptions/Handler.php#L135

Currently the `GrahamCampbell\Exceptions\NewExceptionHandler` does not handle this Exception in any particular way and ends up displaying the whoops page.  

**I made an example repo for reference:**
https://github.com/scrubmx/issue-example/commits/master

**Comment by GrahamCampbell** [comment]
The whoops page override everything. If you'd not like that behaviour, then you can move it lower down in the displayers list. That's sorted by priority. :)

**Comment by scrubmx** [comment]
Check out the example repo. It's a fresh install with one passing test. After installing this package the test is broken. Is up to you but maybe at least we should update the docs?

**Comment by GrahamCampbell** [comment]
I'll take a closer look soon when I have some more time. :)

**Comment by scrubmx** [comment]
Just going to leave a comment for people experiencing this issue.

A temporal fix would be to update your `app/Exceptions/Handler.php` render method like so:

``` php
public function render($request, Exception $exception)
{
   if ($exception instanceof AuthenticationException) {
       return $this->unauthenticated($request, $exception);
   }

   return parent::render($request, $exception);
}
```

**Comment by GrahamCampbell** [comment]
That example repo doesn't look broken. You just didn't change the priorities. Out of the box we don't mimic the laravel behaviour, and have no concept of that unauthenticated method existing. All that is replaced with our displayers.

**Comment by petecoop** [comment]
Is there a way to configure the priorities for this to work? Or is the only option doing as @scrubmx suggests above?

Would it be a good idea for it to work out of the box? I came into this issue yesterday too, as by default Laravel has moved this into the `Exception\Handler`. Previously my understanding of this package would be that I could simply replace the default handler and it work without causing any other issues, but now means making a change somewhere for it to not break default behaviour

**Comment by GrahamCampbell** [comment]
Yes, just change the order of the displayers in the config/exceptions.php file. I would not suggest doing that example pasted above.

**Comment by GrahamCampbell** [comment]
It works how I think it should work out of the box if you see what I mean.

**Comment by scrubmx** [comment]
@GrahamCampbell 

> Out of the box we don't mimic the laravel behavior.

Fair enough, maybe we should add note on the readme then?

The whoops page itself is not the problem. The thing is when using the `auth` middleware it is expected behavior to redirect guests to the login page. Changing the order of the displayers will not achieve this.

A tests like this one: 

``` php
$this->visit('/home')->seePageIs('/login');
```

will still be broken no matter which displayer is being used.

**Comment by GrahamCampbell** [comment]
> will still be broken no matter which displayer is being used.

Nope, that should work so long as you write your own displayer that redirects there.

**Comment by GrahamCampbell** [comment]
I didn't include one out of the box because everyone does this stuff differently. For example, I don't like having redirects for error responses. Instead, I have a real error page with javascript in which redirects the user so that the HTTP spec is implemented correctly.

**Comment by GrahamCampbell** [comment]
For example, if you go to https://styleci.io/account, you get an error 401 page, but then it redirects you through the login process.

**Comment by petecoop** [comment]
I get your point @GrahamCampbell, maybe a note can be added for people that do want to use redirect requests, as it's the default with Laravel it's likely a popular method

**Comment by tucq88** [comment]
Hey @GrahamCampbell, Could you just suggest a sample way to change the displayers priorities to get that work ? I have no idea about changing that array to make it work :(

**Comment by pilot911** [comment]
Remove old code from App\Exceptions\Handler and add next. AuthenticationException will work.

```
`/**
 * Create a Symfony response for the given exception.
 *
 * @param  \Exception  $e
 * @return mixed
 */
protected function convertExceptionToResponse(Exception $e)
{
    if (config('app.debug')) {
        $whoops = new \Whoops\Run;
        $whoops->pushHandler(new \Whoops\Handler\PrettyPageHandler);

        return response()->make(
            $whoops->handleException($e),
            method_exists($e, 'getStatusCode') ? $e->getStatusCode() : 500,
            method_exists($e, 'getHeaders') ? $e->getHeaders() : []
        );
    }

    return parent::convertExceptionToResponse($e);
}
```

**Comment by GrahamCampbell** [comment]
@pilot911 I wouldn't recommend a solution like that.

**Comment by pilot911** [comment]
But what then ?

**Comment by j5lx** [comment]
I'm also interested in what kind of solution you'd recommend. Also:

> Instead, I have a real error page with javascript in which redirects the user so that the HTTP spec is implemented correctly.
> 
> For example, if you go to https://styleci.io/account, you get an error 401 page, but then it redirects you through the login process.

Actually, the way I see it this behaviour *violates* the HTTP spec. From RFC 7235 (Hypertext Transfer Protocol (HTTP/1.1): Authentication), [section 3.1](https://tools.ietf.org/html/rfc7235#section-3.1) (401 Unauthorized):

> The server generating a 401 response MUST send a WWW-Authenticate header field ([Section 4.1](https://tools.ietf.org/html/rfc7235#section-4.1)) containing at least one challenge applicable to the target resource.

I don't see anything about JavaScript redirects there, and I don't see a WWW-Authenticate header in the response for the link you provided. Probably an oversight, and maybe a reason to re-consider this issue. Thoughts?

**Comment by GrahamCampbell** [comment]
> Actually, the way I see it this behaviour violates the HTTP spec.

Not really. It's up to you to apply that header using a middleware.

> But what then ?

Use displayers properly. This package is designed to flexible so you can do whatever you want, through the medium of displayers.

**Comment by tucq88** [comment]
`Use displayers properly.` But how ? You've never told us how to do it `properly` is but you always ask us to do it `properly`. 
This package is great and I `know` it's flexible, I just confuse how to do it right but you never give us an answer :(

**Comment by GrahamCampbell** [comment]
You write a displayer that implements https://github.com/GrahamCampbell/Laravel-Exceptions/blob/master/src/Displayers/DisplayerInterface.php, and then register it in the config file: https://github.com/GrahamCampbell/Laravel-Exceptions/blob/master/config/exceptions.php#L48.

The higher up it is, the earlier it's tried out. The first one that passes the filters as defined in https://github.com/GrahamCampbell/Laravel-Exceptions/blob/master/config/exceptions.php#L69 will be used.

---

From this description, we can see that the debug displayer is always run if in debug, ahead of everything else. If you don't want this, you need to move an existing displayer above it, or write your own, and put it above it in the config file.

---

I intentionally don't spoon feed everything because I want to encourage people to read the whole codebase (and the tests!), and think for themselves, however, I do agree more pointers would be useful for people - I just didn't write any due to lack of time.

**Comment by ctf0** [comment]
this is a continuation of @scrubmx to fix the validation issue aswell for 
> The given data failed to pass validation

```php
// add to the top of file
use Illuminate\Validation\ValidationException;

// ...

public function render($request, Exception $exception)
{
   if ($exception instanceof AuthenticationException) {
       return $this->unauthenticated($request, $exception);
   } elseif ($exception instanceof ValidationException) {
       return $this->convertValidationExceptionToResponse($exception, $request);
   }

   return parent::render($request, $exception);
}
```

am not sure if this issue was also in the 5.2 version of the package but its really focken annoying.

from what i understand that the purpose of the package is to add extra flexibility/features over the original `ExceptionHandler` and if anything was taken away it should be documented so the user dont go in rounds for 2-3 hours just because he/she decided to use this rather than using the included one.

**Comment by GrahamCampbell** [comment]
You don't need hacks like that. Never call other methods on the exception handler. You must embrace the displayers in this package, and put your code in there, otherwise there's no point in you using this package.

**Comment by ctf0** [comment]
well, so far am only using it because of whoops

**Comment by GrahamCampbell** [comment]
You can get whoops yourself just by copying the debug displayer code into your app if you have no interest in using the displayer and filter design pattern enforced in this package (i have no idea what the actual name of this pattern is since I can up with it independently, but I'm sure someone has named it somewhere).

https://github.com/GrahamCampbell/Laravel-Exceptions/blob/master/src/Displayers/DebugDisplayer.php

**Comment by rigeliux** [comment]
ok ok, i know im getting in some closed issue, the thing is... i dont know where to put the code:
1) Create a AuthenticationDisplayer and put it in App/Exceptions/Displayers/AuthenticationDisplayer.php
2) in the display(), put the redirect to login page if not logged.
3) In config/exceptions.php, add the displayer: 'App\Exceptions\Displayers\AuthenticationDisplayer' at top of the displayers list.

then.... what?, i guess im missing something, because i cant get it work

Edit: btw, i copy the HtmlDisplayer, and start from there

**Comment by ghost** [comment]
Hi @GrahamCampbell ,

I've created a custom displayer, that will check if I have an exception type of the Illuminate\Auth\AuthenticationException. That's fine, and it redirects to the route name login by default.

The thing is what code do I need to write that if it's not of that error type, to then follow to the next Displayer?

As:
```php
    public function display(Exception $exception, $id, $code, array $headers)
    {
        //If it's an authentication exception then redirect. Else, show default error.
        if($exception instanceof \Illuminate\Auth\AuthenticationException){
            //In case it's an ajax request, just send the error
            if (Request::expectsJson()) {
                return Response::json(['error' => 'Unauthenticated.'], 401);
            };

            //Redirect to the respective Sprinter configuration Vendor route, or to the default route name 'login' in case it's not configured
            return redirect()->guest(null !== config('sprinter.vendors.graham-campbell.exceptions.routenames.notauthenticated') ? config('sprinter.vendors.graham-campbell.exceptions.routenames.notauthenticated') : route('login'));
        } else {
            ???
        };
    }
```

Thank you.

**Comment by GrahamCampbell** [comment]
> The thing is what code do I need to write that if it's not of that error type, to then follow to the next Displayer?

That's why we have the filters. You should never need to return false from canDisplay: https://github.com/GrahamCampbell/Laravel-Exceptions/blob/master/src/Displayers/DisplayerInterface.php#L51.

**Comment by vedmant** [comment]
This is very inconvenient and breaks app functionality. This is something that needs to be included out of the box. I'm actually moving to use filp/whoops directly because of this issues and overcomplicated approach.

**Comment by GrahamCampbell** [comment]
> I'm actually moving to use filp/whoops directly because of this issues and overcomplicated approach.

Perfectly reasonable. This package is meant to provide a more abstract approach. It's not for everyone. :)

**Comment by mtilokani** [comment]
This issue can be resolved by:

```php
public function render($request, Exception $exception)
    {
        if ($exception instanceof AuthenticationException) {
           return $this->unauthenticated($request, $exception);
        }

        if ($this->isHttpException($exception)) {
            return $this->renderHttpException($exception);
        }

        if (config('app.debug') && \App::isLocal()) {
            return $this->renderExceptionWithWhoops($exception);
        }

        return parent::render($request, $exception);
    }
```

Thanks.

**Comment by GrahamCampbell** [comment]
> This issue can be resolved by:

You should definitely not do that in your handler, since you are abusing the design of this package. You must instead use the displayer system, or you might as well not use this package.

**Comment by mtilokani** [comment]
@GrahamCampbell Thanks.

**Comment by ratatatKE** [comment]
> elseif ($exception instanceof ValidationException) { return $this->convertValidationExceptionToResponse($exception, $request); }

This solved it for me for this issue [https://stackoverflow.com/questions/34610845/laravel-validator-throws-an-exception-instead-of-redirecting-back](url)
