### ISSUE TITLE
[5.3] ->validate(); exception bug

### ISSUE THREAD

**Issue by ctf0** [GrahamCampbell/Laravel-Exceptions#88]
- Laravel Version: 5.3.10
- PHP Version: 7.0.9
- Database Driver & Version: NaN
### Description:

exception made but no redirection & no error msg
### Steps To Reproduce:
- controller

``` php
public function store(Request $request)
{
    $rules = [
        'image' => 'required|image|max:2048',
    ];

    Validator::make($request->all(), $rules)->validate();

    foreach ($request->image as $one) {
        $one->store('images', 'public');
    }

    return url('/')->with('success', 'done');
}
```
- form

``` blade
{{ Form::open(['route' => 'store.files', 'method' => 'POST', 'files'=>true]) }}
    {{ Form::file('image[]',['multiple']) }}
    <hr>
    {{ Form::submit('submit', ['class'=>'btn btn-success']) }}
{{ Form::close() }}
```
- route

``` php
Route::post('/', [
    'as'   => 'store.files',
    'uses' => 'StoreController@store',
]);
```

![screen shot 2016-09-26 at 10 16 45 am](https://cloud.githubusercontent.com/assets/7388088/18827346/b08da39e-83d2-11e6-83cd-8b99f3076370.jpg)

on 5.2 it was working correctly , now when debug is true i get the above, when its false i get an error 500 page.

this is not the case if we instead used

``` php
$this->validate($request, [
   'image' => 'required|image|max:2048',
]);
```

**Comment by GrahamCampbell** [comment]
This is the intended behaviour of this package. This package is opinionated and doesn't permit the use of that method on the laravel exception handler. You need to implement your own "displayer" to use.

**Comment by ctf0** [comment]
i thought that the package follows the same roadmap as laravel , so if user wanted this could be a 100% replacement to the official handler without losing any functionality instead it adds more or am i missing something ?

**Comment by GrahamCampbell** [comment]
It's meant to be an opinionated addon to what Laravel has out of the box. Laravel's out of the box implementation is very light and lacking the power this package provides. Things like content negogiation, or handling different exceptions, or transforming exceptions to allow the message to reach the user are not scalable in the default laravel code.

**Comment by ctf0** [comment]
oh okay , thanx for the headsup :+1:
