### ISSUE TITLE
 multiple languages error and configure.

### ISSUE THREAD

**Issue by douglaszaltron** [GrahamCampbell/Laravel-Exceptions#89]
Place the resource to have the possibility of multiple languages by configuring the config/exceptions.php or Accept-Language is another issue that would be very good is put in Json the possibility of changing the return, for example.

$error = [ 'type' => $ info['name'], 'message' => $info['detail'] ];

{
   "errors": [
     {
       "type": "not_found"
       "message": "O recurso solicitado não foi encontrado, mas pode estar disponível novamente no futuro."
     }
   ]
}

**Comment by kkobold** [comment]
Also, would be awesome to decide where the error template should be loaded from or have the current resources published on views/errors

**Comment by GrahamCampbell** [comment]
The idea with this package is mainly to provide a framework to allow you to implement your own "displayers" and "filters", so it is possible for you to implement localization yourself.

I'm not sure if I want to bake acceptable languages into displayers in the package core here.

**Comment by GrahamCampbell** [comment]
I think we have a PR open currently that addresses this. :)

**Comment by GrahamCampbell** [comment]
At least in part.
