### ISSUE TITLE
Problems with L5.3

### ISSUE THREAD

**Issue by michaelslobodskih** [GrahamCampbell/Laravel-Exceptions#90]
Got this error after proper installation :
2016/11/23 11:34:48 [error] 13728#0: *6489 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught exception 'ErrorException' with message 'Argument 1 passed to Illuminate\Foundation\Exceptions\Handler::__construct() must implement interface Psr\Log\LoggerInterface, instance of Illuminate\Foundation\Application given, called in /home/ms/public_html/ms.saudubna.ru/ms.saudubna.ru/vendor/graham-campbell/exceptions/src/NewExceptionHandler.php on line 51 and defined' in /home/ms/public_html/ms.saudubna.ru/ms.saudubna.ru/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php:43
Stack trace:
#0 /home/ms/public_html/ms.saudubna.ru/ms.saudubna.ru/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(43): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(4096, 'Argument 1 pass...', '/home/ms/public...', 43, Array)
#1 /home/ms/public_html/ms.saudubna.ru/ms.saudubna.ru/vendor/graham-campbell/exceptions/src/NewExceptionHandler.php(51): Illuminate\Foundation\Exceptions\Handler->__construct(Object(Illuminate\Foundation\Applicat...
PHP message: PHP Fatal error:  Uncaught exception 'ErrorException' with message 'Argument 1 passed to Illuminate\Foundation\Exceptions\Handler::__construct() must implement interface Psr\Log\LoggerInterface, instance of Illuminate\Foundation\Application given, called in /home/ms/public_html/ms.saudubna.ru/ms.saudubna.ru/vendor/graham-campbell/exceptions/src/NewExceptionHandler.php on line 51 and defined' in /home/ms/public_html/ms.saudubna.ru/ms.saudubna.ru/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php:43
Stack trace:
#0 /home/ms/public_html/ms.saudubna.ru/ms.saudubna.ru/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(43): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(4096, 'Argument 1 pass...', '/home/ms/public...', 43, Array)
#1 /home/ms/public_html/ms.saudubna.ru/ms.saudubna.ru/vendor/graham-campbell/exceptions/src/NewExceptionHandler.php(51): Illuminate\Foundation\Exce

**Comment by GrahamCampbell** [comment]
Looks like you actually have Laravel 5.2, or a really old 5.3.
